packages:
  - apps/*
  - packages/*

catalog:
  '@antfu/eslint-config': ^5.4.1
  '@eslint-react/eslint-plugin': ^1.53.1
  '@faker-js/faker': ^10.0.0
  '@radix-ui/react-slot': ^1.2.3
  '@t3-oss/env-core': ^0.13.8
  '@tailwindcss/postcss': ^4.1.11
  '@tailwindcss/vite': ^4.0.6
  '@tanstack/match-sorter-utils': ^8.19.4
  '@tanstack/react-devtools': ^0.7.0
  '@tanstack/react-query': ^5.66.5
  '@tanstack/react-query-devtools': ^5.84.2
  '@tanstack/react-router': ^1.132.0
  '@tanstack/react-router-devtools': ^1.132.0
  '@tanstack/react-router-ssr-query': ^1.131.7
  '@tanstack/react-start': ^1.132.0
  '@tanstack/react-table': ^8.21.2
  '@tanstack/router-plugin': ^1.132.0
  '@testing-library/dom': ^10.4.0
  '@testing-library/react': ^16.2.0
  '@turbo/gen': ^2.5.5
  '@types/node': ^22.10.2
  '@types/react': ^19.2.0
  '@types/react-dom': ^19.2.0
  '@vitejs/plugin-react': ^5.0.4
  babel-plugin-react-compiler: ^1.0.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  eslint: 9.37.0
  eslint-plugin-format: ^1.0.1
  eslint-plugin-react: 7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20
  jsdom: ^27.0.0
  lucide-react: ^0.475.0
  next-themes: ^0.4.6
  nitro: 3.0.1-alpha.0
  prettier: ^3.6.2
  prettier-plugin-tailwindcss: ^0.6.14
  react: ^19.2.0
  react-dom: ^19.2.0
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.11
  turbo: ^2.5.8
  tw-animate-css: ^1.3.6
  typescript: ^5.8.3
  vite: ^7.1.7
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.0.5
  web-vitals: ^5.1.0
  zod: ^3.25.76

catalogMode: strict

cleanupUnusedCatalogs: true

engineStrict: true

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - core-js-pure
  - esbuild
